// Generated by CoffeeScript 1.10.0
(function() {
  var appRootPath, converter, fs, path, yaml;

  fs = require("fs");

  yaml = require("js-yaml");

  appRootPath = require("app-root-path");

  path = require("path");

  converter = module.exports = function(filepath) {
    if (!path.extname(filepath)) {
      filepath = filepath + ".yaml";
    }
    return yaml.safeLoad(fs.readFileSync(filepath, 'utf8'));
  };

  converter.resolve = function(filepath) {
    return converter(appRootPath.resolve(filepath));
  };

}).call(this);
